name: publish - wiki

on: workflow_dispatch # Ermöglicht das manuelle Starten des Workflows

jobs:
  publish-wiki:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LUX-components
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB}}
          ref: main
          path: components
      
      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: IHK-GfI/lux-components-workspace.wiki
          token: ${{secrets.GITHUB}}
          ref: master
          path: wiki
          clean: false
      
      - name: Update Wiki
        run: |
          ls -l
          cp -rf components/projects/lux-components-wiki/* wiki/
          cd wiki
          ls -lR
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git status
          git commit -m "Wiki aktualisiert"
          git push
