name: publish - components

on:
  release:
    types: [created]

jobs:
  build:
    if: github.event.release.name && contains(github.event.release.name, 'LUX-Components-Lib')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      -  run: |
           npm install
           npm run pack:components
           cd dist/lux-components-lib
           ls -lR

  publish-npm:
    if: github.event.release.name && contains(github.event.release.name, 'LUX-Components-Lib')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Publish NPM
        run: |
          cd dist/lux-components-lib
          ls -lR
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}

  publish-gpr:
    if: github.event.release.name && contains(github.event.release.name, 'LUX-Components-Lib')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          scope: '@ihk-gfi'
      - name: Publish Github
        run: |
          cd dist/lux-components-lib
          ls -lR
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB}}
