name: smoketest - components

on:
  push:
    paths:
      - 'projects/lux-components-lib/**'

jobs:
  build-demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: |
          npm install
          npm run test:components
          npm run pack:components
          cd dist/lux-components-lib
          ls -lR
